## 6.11 Our First Query

슬슬 import가 많아지니 따로 모아 정리하도록 하자

`server.js`는 express 된 것들과 server 구성에 관련된 코드들만

DB나 model 같은 것들은 따로 빼야함

`server.js`

```js
import express from "express";
import morgan from "morgan";

import globalRouter from "./routers/globalRouter";
import videoRouter from "./routers/videoRouter";
import userRouter from "./routers/userRouter";

const app = express();
const logger = morgan("dev");

app.set("view engine", "pug");
app.set("views", process.cwd() + "/src/views");
app.use(logger);
app.use(express.urlencoded({ extended: true }));
app.use("/", globalRouter);
app.use("/videos", videoRouter);
app.use("/users", userRouter);

export default app;
```

`init.js`

```js
import "./db";
import "./models/Video";
import app from "./server";

const PORT = 4000;

const handleListening = () =>
  console.log(`✅ Server listenting on port http://localhost:${PORT} 🚀`);

app.listen(PORT, handleListening);
```

`package.json`

```json
  "scripts": {
    "dev": "nodemon --exec babel-node src/init.js"
  },
```

이제 `videoController.js` 에 임시 DB, 관련 코드를 지우고

```js
import Video from "../models/Video";
```

model을 import 함

그리고 DB와 연결하려면 `model.find()` 를 사용하면 됨

```js
export const home = (req, res) => {
  Video.find({}, (error, videos) => {
    console.log("error : ", error);
    console.log("videos : ", videos);
  });
  return res.render("home", { pageTitle: "Home", videos: [] });
};
```

`model.find()` 를 사용하는데 2가지 방법이 있는데

1.  callback 함수를 사용하는 방법

2.  promise 를 활용하는 방법

## 6.12 Our First Query part Two

    callback 함수는 무언가가 발생하고 난 다음 호출되는 function

```js
Video.find({}, (error, videos) => {});
```

mongoose 는 이부분을 DB에서 불러 올꺼임

그리고 DB가 반응하면 function 을 실행할꺼임

그 다음에 mongoose는 `error`, `videos` 값을 불러 올꺼임

`(error, videos) => {}` 이부분은

```js
const handleSearch = (error, videos) => {};
```

이것과 같음

home 화면으로 가서 consol.log 값을 보면

```
error : null
videos : []
```

이렇게 나옴

이제

```js
export const home = (req, res) => {
  Video.find({}, (error, videos) => {
    console.log(`error : ${error}`);
    console.log("videos : ", videos);
  });
  console.log("HI");
  return res.render("home", { pageTitle: "Home", videos });
};
```

이렇게 하고 실행해보면

```
HI
GET / 304 232.326 ms - -
error : null
videos : []
```

이렇게 나옴

`HI` 출력보다 `error`,`videos` 출력이 더 늦게됨

이게 `callback` 함수임

**코드에 따라 실행되는 시간이 다름**

이것을 이용해서

```js
export const home = (req, res) => {
  Video.find({}, (error, videos) => {
    return res.render("home", { pageTitle: "Home", videos });
  });
};
```

마지막에 render 할 수 있게

근데 다소 복잡함

그래서 이번에는 두번째 방법을 써볼꺼임

## 6.13 Async Await

`callback` 의 장점은 에러들을 바로 여기에서 볼 수 있다는 거임

추가적인 코드없이도 에러들을 바로 볼 수 있음

```js
export const home = (req, res) => {
  Video.find({}, (error, videos) => {
    if (error) {
      return res.render(`server-error ${error}`);
    }
    return res.render("home", { pageTitle: "Home", videos });
  });
};
```

`promise` 는 `callback` 함수의 최신 버전이라고 생각하면 됨

```js
export const home = async (req, res) => {
  const videos = await Video.find({});
  return res.render("home", { pageTitle: "Home", videos });
};
```

`await` 를 find 앞에 적으면

find는 니가 callback을 필요로 하지 않는다는 걸 알게 됨

그렇기에 find는 찾아낸 비디오를 바로 출력해줌

```js
export const home = async (req, res) => {
  console.log("start");
  const videos = await Video.find({});
  console.log(videos);
  console.log("finish");
  return res.render("home", { pageTitle: "Home", videos: [] });
};
```

```
start
[]
finish
GET / 304 209.843 ms - -
```

보면 바로 출력을 해줌

`await` 가 좋은 이유가 DB에서 값을 받을때까지 기다려준다는거임

`callback` 를 쓰면 부르는 동안 아래의 코드가 실행되어

실행순서가 달라지는 일이 생기는데

`await`를 쓰게 되면 그런일이 없어지다~

그래서 직관적이고 조타~

<br>

그럼 `error`는 어떻게 하냐?

```js
export const home = async (req, res) => {
  try {
    const videos = await Video.find({});
    return res.render("home", { pageTitle: "Home", videos });
  } catch {
    return res.render("server-error");
  }
};
```

트라이 캐치문을 쓰자~

코딩 규칙상 `await`는 function 안에서만 사용이 가능하고

해당 function 에 `async`(asynchronous)를 적어야함

<br><br>

## 6.14 Returns and Renders

사실 callback 함수에서 틀린게

```js
export const home = (req, res) => {
  Video.find({}, (error, videos) => {
    return res.render("home", { pageTitle: "Home", videos });
  });
};
```

find 함수 내에 `return` 을 사용하고 있음

이러면 find 함수의 return 이지 home 함수의 return이 아님

home 어떤것도 return 하지 않고 있는 거임

또 사실 return는 중요치 않음

```js
export const home = (req, res) => {
  Video.find({}, (error, videos) => {
    res.render("home", { pageTitle: "Home", videos });
  });
};
```

return 을 빼고 `render` 만 적어놔도 작동하는 데에 전혀 문제가 없음

중요한건 `render`를 실행했다는 것과 **한번만** 실행했다는 거임

```js
export const home = (req, res) => {
  Video.find({}, (error, videos) => {
    res.render("home", { pageTitle: "Home", videos });
    res.render("home", { pageTitle: "Home", videos });
  });
};
```

이렇게 했다면 오류가 뜸

이미 render 한 것은 다시 render 할 수 없음

`return` 을 써주는 이유는

    해당 functiond이 render 작업 후에 종료되도록 하기 위해서

만약

```js
export const home = (req, res) => {
  Video.find({}, (error, videos) => {
    return res.render("home", { pageTitle: "Home", videos });
  });
  return res.end();
};
```

이렇게 한다면 `find()` 함수를 불러내기 전에 res.end()로 연결을 끊고 home 함수를 종료 해버림
